export const routes = {
  auth: "/auth",
  adminDashboard: "/admindashboard",
  addUser: "adduser",
  editUser: "edituser/:id",
  viewUser: "viewusers",
  addservicecategory: "addservicecategory",
  editservicecategory: "editservicecategory/:id",
  viewServiceCategories: "viewservicecategories",
  addService: "addservice",
  viewServices: "viewservices",
  addPackage: "addPackage",
  viewPackages: "viewPackages",
  addBooking: "addBooking",
  viewBookings: "viewBookings",
  addPayment: "addPayment",
  viewPayments: "viewPayments",
  chats: "chats",
  addComplaint: "addComplaint",
  viewComplaints: "viewComplaints",
  policies: "policies",
  settings: "settings",
  reviewsAndFeedbacks: "reviewsAndFeedbacks",
  faq: "faq",
  "*": "BadRequest",
};
